version: '3'

services:
  data:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "MyStrongPassword123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    networks:
      - mynetwork
    volumes:
      - dbdata:/var/opt/mssql
     

  driver:
    image: driverimage:latest
    depends_on:
      - data
    networks:
      - mynetwork
    ports:
     - "8000:80"
     

networks:
  mynetwork:

volumes:
  dbdata:
